const REQUIRED_DISCLAIMER = [
  'does not constitute legal advice',
  'not a law firm',
];

const FORBIDDEN = [
  'satisfies the requirement',
  'qualifies for',
  'is eligible',
  'is sufficient',
  'guaranteed',
  'will be approved',
  'claude',
  'anthropic',
  'chatgpt',
  'ai generated',
];

describe('LLM Output Validation', () => {
  test('valid document with disclaimer passes', () => {
    const doc = 'This does not constitute legal advice. e2go is not a law firm. The applicant has invested $150,000.';
    const hasDisclaimer = REQUIRED_DISCLAIMER.every(p => doc.toLowerCase().includes(p));
    const hasForbidden = FORBIDDEN.some(p => doc.toLowerCase().includes(p));
    expect(hasDisclaimer).toBe(true);
    expect(hasForbidden).toBe(false);
  });

  test('document missing disclaimer fails', () => {
    const doc = 'The applicant has invested $150,000 in the business.';
    const hasDisclaimer = REQUIRED_DISCLAIMER.every(p => doc.toLowerCase().includes(p));
    expect(hasDisclaimer).toBe(false);
  });

  test('document with legal conclusion fails', () => {
    const doc = 'This does not constitute legal advice. The investment satisfies the requirement.';
    const hasForbidden = FORBIDDEN.some(p => doc.toLowerCase().includes(p));
    expect(hasForbidden).toBe(true);
  });

  test('document with AI tool name fails', () => {
    const doc = 'This does not constitute legal advice. Generated by Claude AI.';
    const hasForbidden = FORBIDDEN.some(p => doc.toLowerCase().includes(p));
    expect(hasForbidden).toBe(true);
  });

  test('document with guarantee language fails', () => {
    const doc = 'This does not constitute legal advice. This application is guaranteed to be approved.';
    const hasForbidden = FORBIDDEN.some(p => doc.toLowerCase().includes(p));
    expect(hasForbidden).toBe(true);
  });

  test('document with qualifies for fails', () => {
    const doc = 'This does not constitute legal advice. The business qualifies for E-2 status.';
    const hasForbidden = FORBIDDEN.some(p => doc.toLowerCase().includes(p));
    expect(hasForbidden).toBe(true);
  });

  test('document with is eligible fails', () => {
    const doc = 'This does not constitute legal advice. The applicant is eligible for the visa.';
    const hasForbidden = FORBIDDEN.some(p => doc.toLowerCase().includes(p));
    expect(hasForbidden).toBe(true);
  });

  test('document with is sufficient fails', () => {
    const doc = 'This does not constitute legal advice. The investment is sufficient.';
    const hasForbidden = FORBIDDEN.some(p => doc.toLowerCase().includes(p));
    expect(hasForbidden).toBe(true);
  });
});