"use client";

import { useState, useRef, Suspense } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import Link from "next/link";

function TermsRequiredContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const next = searchParams.get("next") || "/apply/module1";

  const termsBoxRef = useRef<HTMLDivElement>(null);
  const [hasScrolledTerms, setHasScrolledTerms] = useState(false);
  const [termsAccepted, setTermsAccepted] = useState(false);
  const [accepting, setAccepting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleTermsScroll = () => {
    const el = termsBoxRef.current;
    if (!el) return;
    const atBottom = el.scrollHeight - el.scrollTop <= el.clientHeight + 10;
    if (atBottom) setHasScrolledTerms(true);
  };

  const handleAccept = async () => {
    if (!termsAccepted || accepting) return;
    setAccepting(true);
    setError(null);

    try {
      const res = await fetch("/api/auth/accept-terms", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
      });

      const data = await res.json();

      if (!res.ok) {
        setError(data.error || "Failed to record acceptance. Please try again.");
        setAccepting(false);
        return;
      }

      // Acceptance recorded — redirect to intended destination
      router.push(next);
    } catch {
      setError("Something went wrong. Please try again.");
      setAccepting(false);
    }
  };

  return (
    <div
      className="min-h-screen flex items-center justify-center px-4"
      style={{ background: "#0a0a0a" }}
    >
      <div
        className="w-full max-w-lg p-8"
        style={{
          background: "rgba(201,168,76,0.02)",
          border: "1px solid rgba(201,168,76,0.12)",
          borderRadius: 0,
        }}
      >
        <div
          className="w-12 h-12 flex items-center justify-center mx-auto mb-6"
          style={{ background: "rgba(201,168,76,0.08)" }}
        >
          <svg
            className="w-6 h-6"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
            style={{ color: "#C9A84C" }}
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={1.5}
              d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
            />
          </svg>
        </div>

        <h1
          className="text-xl mb-3 text-center"
          style={{
            fontFamily: "'Cormorant Garamond', serif",
            fontWeight: 300,
            fontStyle: "italic",
            color: "#f5f0e8",
            fontSize: "24px",
          }}
        >
          Terms of Service acceptance required
        </h1>

        <p
          className="mb-6 text-center"
          style={{
            fontFamily: "'DM Sans', sans-serif",
            fontWeight: 300,
            fontSize: "14px",
            lineHeight: 1.7,
            color: "rgba(245,240,232,0.6)",
          }}
        >
          Before accessing your application, please review and accept
          our Terms of Service.
        </p>

        {/* Scrollable terms summary */}
        <div
          ref={termsBoxRef}
          onScroll={handleTermsScroll}
          style={{
            height: "240px",
            overflowY: "auto",
            border: "1px solid rgba(201,168,76,0.2)",
            padding: "16px",
            marginBottom: "20px",
            background: "rgba(201,168,76,0.02)",
            fontSize: "12px",
            lineHeight: "1.7",
            color: "rgba(245,240,232,0.6)",
          }}
        >
          <p style={{ fontWeight: 500, color: "rgba(245,240,232,0.8)", marginBottom: "12px", fontSize: "13px" }}>
            E2go Terms of Service Summary
          </p>
          <p style={{ marginBottom: "10px" }}>
            E2go is a document preparation platform. It is not a law firm
            and does not provide legal advice. No attorney-client relationship
            is created by using this platform.
          </p>
          <p style={{ marginBottom: "10px" }}>
            Documents generated by E2go are produced using artificial
            intelligence. AI documents may contain errors. You are
            responsible for reading every document carefully and verifying
            its accuracy before submitting it to any government authority.
            E2go&apos;s responsibility ends at the point of download.
          </p>
          <p style={{ marginBottom: "10px" }}>
            E2go does not guarantee visa approval. All consular decisions
            are made by U.S. government officers exercising independent
            discretion. A strong eligibility score does not mean your visa
            will be approved.
          </p>
          <p style={{ marginBottom: "10px" }}>
            Payment is final once document generation has begun. If you
            have not started generation, you may request a refund within
            72 hours of purchase.
          </p>
          <p style={{ marginBottom: "10px" }}>
            Your personal information is encrypted and is not sold to
            third parties. If you are in Canada, PIPEDA applies to your
            data. If you are in the EU, GDPR applies. If you are in
            California, CCPA applies. You may request deletion of your
            data at any time by contacting privacy@e2go.app.
          </p>
          <p style={{ marginBottom: "10px" }}>
            These Terms are governed by the laws of Texas, United States.
            Disputes are resolved by binding arbitration.
          </p>
          <p style={{ marginBottom: "10px" }}>
            By accepting, you confirm you have read these Terms, you are
            at least 18 years old, and you agree to be bound by them.
          </p>
          <p>
            Read the full Terms of Service at{" "}
            <a
              href="/terms"
              target="_blank"
              rel="noopener noreferrer"
              style={{ color: "#C9A84C", textDecoration: "underline" }}
            >
              e2go.app/terms
            </a>
          </p>
        </div>

        {/* Terms checkbox — disabled until scroll */}
        <div
          style={{
            display: "flex",
            alignItems: "flex-start",
            gap: "12px",
            marginBottom: "16px",
            opacity: hasScrolledTerms ? 1 : 0.35,
            pointerEvents: hasScrolledTerms ? "auto" : "none",
          }}
        >
          <input
            type="checkbox"
            id="terms-accept"
            checked={termsAccepted}
            onChange={(e) => setTermsAccepted(e.target.checked)}
            disabled={!hasScrolledTerms}
            style={{
              width: "16px",
              height: "16px",
              marginTop: "2px",
              accentColor: "#C9A84C",
              cursor: hasScrolledTerms ? "pointer" : "not-allowed",
              flexShrink: 0,
            }}
          />
          <label
            htmlFor="terms-accept"
            style={{
              fontSize: "13px",
              color: "rgba(245,240,232,0.7)",
              lineHeight: "1.5",
              cursor: hasScrolledTerms ? "pointer" : "default",
            }}
          >
            I have read and agree to the{" "}
            <a
              href="/terms"
              target="_blank"
              rel="noopener noreferrer"
              style={{ color: "#C9A84C", textDecoration: "underline" }}
            >
              Terms of Service
            </a>
            . I understand that E2go is not a law firm, does not provide
            legal advice, and that I am responsible for reviewing all
            generated documents before submission.
          </label>
        </div>

        {!hasScrolledTerms && (
          <p style={{ fontSize: "11px", color: "rgba(245,240,232,0.4)", marginBottom: "16px" }}>
            Please scroll through the terms above before accepting.
          </p>
        )}

        {error && (
          <div
            style={{
              padding: "10px 14px",
              background: "rgba(239,68,68,0.08)",
              border: "1px solid rgba(239,68,68,0.2)",
              fontSize: "13px",
              color: "rgba(245,240,232,0.7)",
              marginBottom: "16px",
              lineHeight: 1.5,
            }}
          >
            {error}
          </div>
        )}

        <button
          onClick={handleAccept}
          disabled={!hasScrolledTerms || !termsAccepted || accepting}
          className="w-full py-3 font-medium transition-colors"
          style={{
            background: !hasScrolledTerms || !termsAccepted
              ? "rgba(201,168,76,0.3)"
              : "#C9A84C",
            color: "#0a0a0a",
            borderRadius: 0,
            cursor: !hasScrolledTerms || !termsAccepted || accepting
              ? "not-allowed"
              : "pointer",
            fontSize: "14px",
            letterSpacing: "0.04em",
            fontFamily: "'DM Sans', sans-serif",
            opacity: accepting ? 0.6 : 1,
          }}
        >
          {accepting ? "Recording acceptance..." : "Accept and continue"}
        </button>

        <div className="flex flex-col gap-3 mt-4">
          <Link
            href="/terms"
            className="block w-full py-3 text-center font-medium transition-colors"
            style={{
              background: "transparent",
              color: "rgba(245,240,232,0.6)",
              border: "1px solid rgba(201,168,76,0.2)",
              borderRadius: 0,
              fontSize: "13px",
              textDecoration: "none",
            }}
          >
            Read full Terms of Service
          </Link>

          <Link
            href="/dashboard"
            className="block w-full py-3 text-center font-medium transition-colors"
            style={{
              background: "transparent",
              color: "rgba(245,240,232,0.4)",
              border: "none",
              borderRadius: 0,
              fontSize: "12px",
              textDecoration: "none",
            }}
          >
            ← Back to dashboard
          </Link>
        </div>
      </div>
    </div>
  );
}

export default function TermsRequiredPage() {
  return (
    <Suspense
      fallback={
        <div
          className="min-h-screen flex items-center justify-center"
          style={{ background: "#0a0a0a" }}
        >
          <div className="w-8 h-8 border-2 border-[#C9A84C] border-t-transparent rounded-full animate-spin" />
        </div>
      }
    >
      <TermsRequiredContent />
    </Suspense>
  );
}
