"use client";

import Link from "next/link";

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen flex flex-col" style={{ background: "#0a0a0a" }}>
      <header className="sticky top-0 z-50" style={{ background: "#0a0a0a", borderBottom: "1px solid rgba(201,168,76,0.2)" }}>
        <div className="flex justify-between items-center h-16 px-4 max-w-4xl mx-auto w-full">
          <Link href="/" className="flex items-center gap-2">
            <span className="text-xl font-bold" style={{ color: "#C9A84C", fontFamily: "'Cormorant Garamond', serif", fontWeight: 300 }}>
              e2go<span style={{ color: "#f5f0e8" }}>.app</span>
            </span>
          </Link>
          <Link href="/" style={{ color: "rgba(245,240,232,0.7)", fontSize: "14px", textDecoration: "none" }}>
            ← Back to home
          </Link>
        </div>
      </header>

      <main className="flex-1 px-4 py-12 max-w-3xl mx-auto w-full">
        <h1 className="text-4xl font-light mb-4" style={{ fontFamily: "'Cormorant Garamond', serif", color: "#f5f0e8", fontWeight: 300 }}>
          Terms of Service
        </h1>
        <p className="mb-8" style={{ fontSize: "14px", color: "rgba(245,240,232,0.5)", fontFamily: "'DM Sans', sans-serif" }}>
          Last updated: June 2026
        </p>

        <div style={{ color: "rgba(245,240,232,0.75)", fontFamily: "'DM Sans', sans-serif", fontWeight: 300, lineHeight: 1.7, fontSize: "15px" }}>
          <p className="mb-6">
            Please read these Terms of Service (&apos;Terms&apos;) carefully before using the E2go application (&apos;App&apos;) operated by E2Pathway Inc. (&apos;Company&apos;, &apos;we&apos;, &apos;us&apos;, or &apos;our&apos;). By accessing or using the App, you agree to be bound by these Terms.
          </p>

          <h2 className="text-2xl mb-4 mt-8" style={{ fontFamily: "'Cormorant Garamond', serif", color: "#f5f0e8", fontWeight: 400 }}>1. ACCEPTANCE OF TERMS</h2>
          <p className="mb-4">
            By creating an account, accessing, or using E2go, you acknowledge that you have read, understood, and agree to be bound by these Terms and our Privacy Policy. If you do not agree, do not use the App.
          </p>
          <p className="mb-4">
            These Terms constitute a binding legal agreement between you (&apos;User&apos;) and the Company. If you are using the App on behalf of a third party, you represent that you have authority to bind that party to these Terms.
          </p>

          <h2 className="text-2xl mb-4 mt-8" style={{ fontFamily: "'Cormorant Garamond', serif", color: "#f5f0e8", fontWeight: 400 }}>2. DESCRIPTION OF SERVICE</h2>
          <p className="mb-4">
            E2go is a self-service document preparation and interview readiness platform designed to assist applicants preparing materials in connection with U.S. E-2 Treaty Investor visa applications. The App provides:
          </p>
          <ul className="list-disc ml-6 mb-4 space-y-2">
            <li>Guided document preparation assistance including DS-160 reference sheets, cover letter drafts, business plan templates, source of funds chronologies, organizational charts, and hiring plans;</li>
            <li>An application readiness assessment tool that evaluates the completeness and quality of preparation materials;</li>
            <li>An interview simulation tool for practice purposes;</li>
            <li>A compliance calendar with preparation milestones;</li>
            <li>Educational content about the E-2 visa process;</li>
            <li>Optional referral services connecting users with third-party professionals.</li>
          </ul>

          <h2 className="text-2xl mb-4 mt-8" style={{ fontFamily: "'Cormorant Garamond', serif", color: "#f5f0e8", fontWeight: 400 }}>3. NOT LEGAL ADVICE — CRITICAL DISCLAIMER</h2>
          <p className="mb-4 font-medium" style={{ color: "#f5f0e8" }}>
            THE APP DOES NOT PROVIDE LEGAL ADVICE. THE COMPANY IS NOT A LAW FIRM. NO ATTORNEY-CLIENT RELATIONSHIP IS CREATED BY USE OF THE APP.
          </p>
          <p className="mb-4">
            <strong>Educational Purpose Only.</strong> All content, materials, templates, scores, assessments, and outputs generated by the App are provided for educational and organizational purposes only. They do not constitute legal advice, immigration advice, or any professional regulated service.
          </p>
          <p className="mb-4">
            <strong>No Guarantee of Outcome.</strong> The Company makes no representation, warranty, or guarantee that use of the App will result in visa approval, that materials generated by the App are legally sufficient for any purpose, or that any assessment or score reflects actual approval likelihood. Visa decisions are made solely by U.S. Consular Officers and USCIS officials, who exercise independent discretionary judgment. No preparation tool can predict or ensure any particular outcome.
          </p>
          <p className="mb-4">
            <strong>User Responsibility.</strong> You are solely responsible for the accuracy of all information you provide, all decisions you make about your application, and the ultimate content of any documents submitted to a consulate or government agency.
          </p>

          <h2 className="text-2xl mb-4 mt-8" style={{ fontFamily: "'Cormorant Garamond', serif", color: "#f5f0e8", fontWeight: 400 }}>4. ACCOUNTS AND REGISTRATION</h2>
          <p className="mb-4">
            You must be at least 18 years of age to use the App. You are responsible for maintaining the confidentiality of your account credentials. You represent that all information you provide during registration and throughout the App is truthful, accurate, and complete. Each E-2 application must be associated with its own account or application slot.
          </p>

          <h2 className="text-2xl mb-4 mt-8" style={{ fontFamily: "'Cormorant Garamond', serif", color: "#f5f0e8", fontWeight: 400 }}>5. SUBSCRIPTIONS, PAYMENTS, AND REFUNDS</h2>
          <p className="mb-4">
            The App is offered on a subscription basis. Current pricing and plan details are available on our pricing page. Prices are in USD and subject to change with 30 days&apos; notice. Due to the nature of digital products and immediate access to document generation, refunds are available within 14 days of initial purchase if no documents have been generated and Module 1 has not been started. Refunds equal full payment minus Stripe processing fees. No refunds are issued after documents have been generated or on the basis of visa denial.
          </p>

          <h2 className="text-2xl mb-4 mt-8" style={{ fontFamily: "'Cormorant Garamond', serif", color: "#f5f0e8", fontWeight: 400 }}>6. ACCEPTABLE USE</h2>
          <p className="mb-4">You agree not to:</p>
          <ul className="list-disc ml-6 mb-4 space-y-2">
            <li>Use the App to generate documents for any person other than yourself or covered dependents under your plan;</li>
            <li>Share, resell, redistribute, or sublicense access to the App or any generated materials to third parties;</li>
            <li>Attempt to reverse-engineer, decompile, or extract proprietary content including question sets, scoring logic, or template structures;</li>
            <li>Use automated tools, bots, or scrapers to access or interact with the App;</li>
            <li>Submit false or misleading information to generate documents intended for use in any government filing;</li>
            <li>Use the App for any unlawful purpose or in violation of any applicable law.</li>
          </ul>

          <h2 className="text-2xl mb-4 mt-8" style={{ fontFamily: "'Cormorant Garamond', serif", color: "#f5f0e8", fontWeight: 400 }}>7. INTELLECTUAL PROPERTY</h2>
          <p className="mb-4">
            The App, including all content, templates, question sets, scoring algorithms, software, design, and generated document structures, is owned by the Company and protected by applicable intellectual property laws. Subject to these Terms, the Company grants you a limited, non-exclusive, non-transferable license to use the App and download generated documents solely for your personal E-2 visa application. You retain ownership of the personal information and content you input into the App.
          </p>

          <h2 className="text-2xl mb-4 mt-8" style={{ fontFamily: "'Cormorant Garamond', serif", color: "#f5f0e8", fontWeight: 400 }}>8. DISCLAIMERS AND LIMITATION OF LIABILITY</h2>
          <p className="mb-4 font-medium" style={{ color: "#f5f0e8" }}>
            THE APP IS PROVIDED &apos;AS IS&apos; AND &apos;AS AVAILABLE&apos; WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED.
          </p>
          <p className="mb-4">
            TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE COMPANY&apos;S TOTAL LIABILITY TO YOU FOR ANY CLAIM ARISING FROM OR RELATED TO THESE TERMS OR YOUR USE OF THE APP SHALL NOT EXCEED THE AMOUNT YOU PAID TO THE COMPANY IN THE 12 MONTHS PRECEDING THE CLAIM. THE COMPANY SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOST PROFITS, LOST VISA OPPORTUNITY, OR RELOCATION COSTS.
          </p>

          <h2 className="text-2xl mb-4 mt-8" style={{ fontFamily: "'Cormorant Garamond', serif", color: "#f5f0e8", fontWeight: 400 }}>9. GOVERNING LAW AND DISPUTE RESOLUTION</h2>
          <p className="mb-4">
            These Terms are governed by the laws of the Province of Ontario and the federal laws of Canada applicable therein. Any dispute arising under these Terms shall first be submitted to good-faith negotiation for 30 days. If unresolved, disputes shall be submitted to binding arbitration in Toronto, Ontario, under the applicable rules of the ADR Institute of Canada.
          </p>

          <h2 className="text-2xl mb-4 mt-8" style={{ fontFamily: "'Cormorant Garamond', serif", color: "#f5f0e8", fontWeight: 400 }}>10. MODIFICATIONS</h2>
          <p className="mb-4">
            The Company reserves the right to modify these Terms at any time. Material changes will be communicated via email or in-app notification at least 14 days before taking effect. Continued use after the effective date constitutes acceptance of the revised Terms.
          </p>

          <h2 className="text-2xl mb-4 mt-8" style={{ fontFamily: "'Cormorant Garamond', serif", color: "#f5f0e8", fontWeight: 400 }}>11. CONTACT</h2>
          <p className="mb-4">
            For questions about these Terms, contact: support@e2go.app
          </p>
        </div>

        <div className="mt-12 pt-8" style={{ borderTop: "1px solid rgba(201,168,76,0.2)" }}>
          <Link href="/" style={{ color: "#C9A84C", fontSize: "14px", textDecoration: "none" }}>
            ← Back to home
          </Link>
        </div>
      </main>
    </div>
  );
}