-- Interview Prep Kits — cached dossier per application
-- Generated by LLM from scoreCase() + all case data
-- Re-generates when > 7 days old or manual regenerate

CREATE TABLE IF NOT EXISTS interview_prep_kits (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  application_id  uuid NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
  user_id         uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  kit_json        jsonb NOT NULL,
  model_used      text NOT NULL DEFAULT 'xiaomi/mimo-v2.5-pro',
  generated_at    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (application_id)
);

ALTER TABLE interview_prep_kits ENABLE ROW LEVEL SECURITY;

-- Users can only read their own kits
CREATE POLICY "Users read own prep kits"
  ON interview_prep_kits FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

-- Service role writes kits (API routes use service client)
CREATE POLICY "Service role manages prep kits"
  ON interview_prep_kits FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Index for fast lookup by application
CREATE INDEX IF NOT EXISTS idx_prep_kits_application_id
  ON interview_prep_kits (application_id);

CREATE INDEX IF NOT EXISTS idx_prep_kits_user_id
  ON interview_prep_kits (user_id);
